"""ZK proof type definitions for the Python interface."""

from __future__ import annotations

from dataclasses import dataclass
from typing import Optional


@dataclass
class ZKProof:
    """A zero-knowledge proof generated by the Rust ZK circuits."""

    proof_bytes: bytes
    public_inputs: dict
    circuit_type: str  # "baseline" | "improvement" | "lineage" | "non_regression"
    verification_key_hash: str = ""


@dataclass
class ProofRequest:
    """Request to generate a ZK proof."""

    circuit_type: str
    private_inputs: dict
    public_inputs: dict


@dataclass
class ProofResult:
    """Result of proof generation."""

    success: bool
    proof: Optional[ZKProof] = None
    generation_time_ms: float = 0.0
    error: Optional[str] = None
